- block:

    - name: stop nova-compute
      service:
        name: "{{ item }}"
        state: stopped
      with_items:
        - openstack-nova-compute
    
    - name: add mount point for nova
      mount:
        src: "{{ hostvars[customer+'-controller'].ansible_host }}:/srv/nova-nfs"
        path: /var/lib/nova/instances
        fstype: nfs
        opts: _netdev,defaults
        state: mounted

    #semodule -i /root/my-virtlogd.pp

    - name: selinux should allow libvirt to use nfs
      seboolean:
        name: virt_use_nfs
        persistent: yes
        state: yes
      delegate_to: layer1

    - name: start nova-compute
      service:
        name: "{{ item }}"
        state: started
      with_items:
        - openstack-nova-compute    

  when: mode=='create'
