- block:
    - name: pre-load some modules
      modprobe:
        name: "{{ item }}"
        state: present
      with_items:
        - configfs
        - target_core_mod

    #- debug: var=hostvars

    - name: install answer-file
      template:
        src: ../files/"{{ answer_file }}"
        dest: /root/"{{ answer_file }}"
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx

    - name: check for packstack already run (remove /root/packstack.done to re-run)
      stat:
        path: /root/packstack.done
      register: packstack_installed

    - name: "### Step 3: Run Packstack to install OpenStack"
      shell: packstack --answer-file="{{ answer_file }}" &> ~/packstack_install.out
      when: packstack_installed.stat.exists == False
    
    - name: set state "packstack already run"
      file:
        path: /root/packstack.done
        state: touch

  when: mode=='create'
